/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RPS } from "./RPS";
export * as factories from "./factories";
export { RPS__factory } from "./factories/RPS__factory";
